---
server:
  contextPath: /omar-geoscript
  port: 8083
---
geoscript:
  evwhs:
    #url: 'https://evwhs.digitalglobe.com/mapservice/wmsaccess?connectid=eb33ba21-1782-4ffc-8a5c-4854e21effb9&version=1.3.0&request=GetCapabilities'
    url: 'https://evwhs.digitalglobe.com/mapservice/wmsaccess?connectid=a59618a4-3656-4b09-ba85-934f162bd9d6&version=1.3.0&request=GetCapabilities'
    username: ''
    password: ''

---
wms:  
  styles:
      byFileType:
          adrg:
            filter: file_type='adrg'
            color:
              r: 50
              g: 111
              b: 111
              a: 255
          aaigrid:
            filter: file_type='aaigrid'
            color: pink
          cadrg:
            filter: file_type='cadrg'
            color:
              r: 0
              g: 255
              b: 255
              a: 255
          ccf:
            filter: file_type='ccf'
            color:
              r: 128
              g: 100
              b: 255
              a: 255
          cib:
            filter: file_type='cib'
            color:
              r: 0
              g: 128
              b: 128
              a: 255
          doqq:
            filter: file_type='doqq'
            color: purple
          dted:
            filter: file_type='dted'
            color:
              r: 0
              g: 255
              b: 0
              a: 255
          imagine_hfa:
            filter: file_type='imagine_hfa'
            color: lightGray
          jpeg:
            filter: file_type='jpeg'
            color:
              r: 255
              g: 255
              b: 0
              a: 255
          jpeg2000:
            filter: file_type='jpeg2000'
            color:
              r: 255
              g: 200
              b: 0
              a: 255
          landsat7:
            filter: file_type='landsat7'
            color:
              r: 255
              g: 0
              b: 255
              a: 255
          mrsid:
            filter: file_type='mrsid'
            color:
              r: 0
              g: 188
              b: 0
              a: 255
          nitf:
            filter: file_type='nitf'
            color:
              r: 0
              g: 0
              b: 255
              a: 255
          tiff:
            filter: file_type='tiff'
            color:
              r: 255
              g: 0
              b: 0
              a: 255
          mpeg:
            filter: file_type='mpeg'
            color:
              r: 164
              g: 254
              b: 255
              a: 255
          unspecified:
            filter: file_type='unspecified'
            color: white
      bySensorType:
          'ACES_YOGI-HRI1':
            filter: mission_id='ACES_YOGI-HRI1'
            color:
              r: 255
              g: 0
              b: 0
              a: 255
          'ACES_YOGI-HRI2':
            filter: mission_id='ACES_YOGI-HRI2'
            color:
              r: 255
              g: 0
              b: 0
              a: 255
          'ACES_YOGI-HRI3':
            filter: mission_id='ACES_YOGI-HRI3'
            color:
              r: 255
              g: 0
              b: 0
              a: 255
          'ACES_YOGI-HSI':
            filter: mission_id='ACES_YOGI-HSI'
            color:
              r: 255
              g: 255
              b: 0
              a: 255
          ALPHA:
            filter: mission_id='ALPHA'
            color:
              r: 255
              g: 0
              b: 255
              a: 255
          BRAVO:
            filter: mission_id='BRAVO'
            color:
              r: 0
              g: 255
              b: 0
              a: 255
          CHARLIE:
            filter: mission_id='CHARLIE'
            color:
              r: 0
              g: 255
              b: 255
              a: 255
          DELTA:
            filter: mission_id='DELTA'
            color:
              r: 0
              g: 0
              b: 255
              a: 255
          unspecified:
            filter: mission_id='unspecified'
            color:
              r: 255
              g: 255
              b: 255
              a: 255
      byVideoType:
          mpeg:
            filter: filename like '%mpg'
            color:
              r: 255
              g: 0
              b: 0
              a: 255
