---
geoscript:
  evwhs:
    #url: 'https://evwhs.digitalglobe.com/mapservice/wmsaccess?connectid=eb33ba21-1782-4ffc-8a5c-4854e21effb9&version=1.3.0&request=GetCapabilities'
    url: 'https://evwhs.digitalglobe.com/mapservice/wmsaccess?connectid=a59618a4-3656-4b09-ba85-934f162bd9d6&version=1.3.0&request=GetCapabilities'
    username: ''
    password: ''
